### ISSUE TITLE
Windows 7: AttributeError: module 'os' has no attribute 'geteuid'

### ISSUE THREAD

**Issue by twallace12** [shirosaidev/sharesniffer#2]
This is happening on my Windows 7 PC:

Traceback (most recent call last):
  File "C:/python/sharesniffer.py", line 494, in <module>
    shares = sniff_network()
  File "C:/python/sharesniffer.py", line 309, in sniff_network
    if os.geteuid():
AttributeError: module 'os' has no attribute 'geteuid'

**Comment by shirosaidev** [comment]
sharesniffer works in macos and linux
